StudyCity/settings.py, accounts/templates/accounts/password_reset.html, accounts/templates/accounts/password_reset_complete.html, accounts/templates/accounts/password_reset_confirm.html, accounts/templates/accounts/password_reset_done.html, accounts/urls.py
=> add password reset feature

accounts/views.py, accounts/yelp_api.py, manage.py
updates:
1. created yelp_api.py to serve search requests (two types: term/location search and business ID search)
2. imported class from above file into views.py and setup integration example under index function where output is printed
3. updated manage.py to include dotenv.load_dotenv()
Note: please create a local .env file within your local repo with the Yelp API key provided on Slack
=> integrated yelp api, ticket #35

accounts/templates/accounts/index.html, accounts/templates/accounts/location_detail.html, accounts/urls.py, accounts/views.py, accounts/yelp_api.py, manage.py, requirements.txt
=> Location page

accounts/templates/accounts/index.html, accounts/views.py
-added IndexError exception handling back to 'comfort' filter
=> added exception handling back

accounts/templates/accounts/location_detail.html, accounts/views.py
Show the number of reviews submitted for each location profile page.
Show average ratings on location profile page.
=> Hang working branch

accounts/templates/accounts/index.html, accounts/templates/accounts/location_detail.html, accounts/templates/accounts/profile.html, accounts/templates/accounts/user.html
Edited : 
1. Index (Search) page
2. location_detail page
3. profile page
4. user page
to have  navigation links to other relevant pages (search, profile, login, logout etc ) based on whether the user is logged in or not, and based on the possible need for the user on that page.
=> Ssnewbranch

accounts/models.py, requirements.txt
- added datetime to requirements.txt
- modified the slug for claimed_business_name and verified_yelp_id to a timestamp
- removed original slug implementation
=> updated slug in Profile model save

accounts/templates/accounts/index.html, accounts/templates/accounts/location_detail.html, static/css/index.css, static/css/styles.css, templates/nav.html
- moved styles into separate css files
- refactored navbar into a base template file
=> refactored formats

accounts/templates/accounts/index.html, static/js/index.js
- added loading indicator
- if the location is loading, submit button will be disabled, so user won't be able to perform a search
=> Add loading state

accounts/templates/accounts/index.html, accounts/views.py
1. Added the 311 check filter (unchecked by default)
2. Implemented its functionality to filter out responses. When checked, it  displays only the study spaces which don't have 311 complaints
=> Ssnew branch

accounts/templates/accounts/location_detail.html
=> change form link

accounts/templates/accounts/location_detail.html, accounts/views.py
Add a map to the location detail page
=> add a map to the location's page and provide directions

accounts/views.py
-resolves bug defined in issue #156 where the rendered coordinate list was populated prior to location filtering and resulted in pins appearing for locations that we're not provided to the user
=> updated coordinate list population after filtering in views.py

accounts/models.py
Issue 178: Larger text box for review and text wrapping
=> Issue 178: larger review text box and wrapping

accounts/templates/accounts/location_detail.html, accounts/templates/accounts/review_confirm_delete.html, accounts/templates/accounts/review_delete_suc.html, accounts/tests/test_views.py, accounts/urls.py, accounts/views.py
fixed issue161: Users can delete their reviews on location page
fixed issue166: Avoid resubmitting the form
=> Hang debug

StudyCity/urls.py, accounts/forms.py, accounts/urls.py
If a user tries to reset password via an invalid / unregistered email, throw an error.
=> Simransbranch

accounts/forms.py, accounts/models.py, accounts/views.py
-implemented clean func in RegisterForm class (forms.py) to raise validation error if user attempts to create >1 accounts with the same email address
=> added validation error for registering duplicate email addresses

accounts/advertising.py, accounts/views.py
-added missing item['advertising'] = False assignments on dangling conditional statements in advertising.py
=> conditional bug fix

accounts/tests/test_views.py
=> add some unit_tests

accounts/views.py
=> fixed issue 223 location map bug
